/**
 * Australian FSANZ allergen data — exclusions, definitions, and code mappings.
 * Kept in a separate file to meet the utility size limit.
 */

import type { Allergen } from './australian-allergens';

/**
 * Terms that appear to contain an allergen keyword but do NOT indicate the allergen.
 * Applied before keyword matching to prevent false positives.
 */
export const ALLERGEN_EXCLUSIONS: Record<string, string[]> = {
  eggs: ['eggplant', 'egg-free', 'egg free', 'no egg'],
  nuts: [
    'nutmeg',
    'coconut',
    'butternut',
    'doughnut',
    'donut',
    'nut-free',
    'nut free',
    'no nuts',
    'peanut-free',
    'tree nut-free',
    'chestnut',
  ],
  milk: ['milk-free', 'dairy-free', 'milk free', 'dairy free', 'no dairy', 'no milk', 'oat milk'],
  gluten: ['gluten-free', 'gluten free', 'wheat-free', 'wheat free', 'no gluten'],
  soy: ['soy-free', 'soy free', 'no soy'],
  fish: ['fish-free', 'fish free', 'no fish', 'starfish'],
  shellfish: ['shellfish-free', 'shellfish free', 'no shellfish'],
  sesame: ['sesame-free', 'sesame free', 'no sesame'],
  lupin: ['lupin-free', 'lupin free'],
  sulphites: ['sulphite-free', 'sulphite free', 'sulfite-free'],
  mustard: ['mustard-free', 'mustard free', 'no mustard'],
};

/**
 * Mapping from old allergen codes to new consolidated codes
 */
export const OLD_CODE_TO_NEW_CODE: Record<string, string> = {
  crustacea: 'shellfish',
  molluscs: 'shellfish',
  peanuts: 'nuts',
  tree_nuts: 'nuts',
  wheat: 'gluten',
};

/**
 * Consolidated allergen list according to food safety best practices.
 * Combines related allergens: shellfish (crustacea + molluscs), nuts (peanuts + tree_nuts), gluten (includes wheat).
 */
export const AUSTRALIAN_ALLERGENS: Allergen[] = [
  {
    code: 'nuts',
    displayName: 'Nuts',
    description: 'Peanuts and tree nuts (almonds, cashews, walnuts, etc.)',
    commonNames: [
      'peanut',
      'peanuts',
      'groundnut',
      'groundnuts',
      'arachis',
      'monkey nut',
      'almond',
      'almonds',
      'cashew',
      'cashews',
      'walnut',
      'walnuts',
      'pecan',
      'pecans',
      'hazelnut',
      'hazelnuts',
      'pistachio',
      'pistachios',
      'brazil nut',
      'brazil nuts',
      'macadamia',
      'macadamias',
      'pine nut',
      'pine nuts',
      'candlenut',
      'candlenuts',
      'marcona',
      'praline',
      'marzipan',
      'nougat',
      'nut butter',
      'nut oil',
      'nut paste',
    ],
    icon: 'Nut',
  },
  {
    code: 'milk',
    displayName: 'Milk',
    description: 'Milk and milk products (dairy)',
    commonNames: [
      'milk',
      'dairy',
      'cream',
      'butter',
      'cheese',
      'yogurt',
      'yoghurt',
      'lactose',
      'whey',
      'casein',
      'caseinate',
      'ghee',
      'buttermilk',
      'curd',
      'paneer',
      'kefir',
      'lactalbumin',
      'lactoglobulin',
      'skimmed milk',
      'whole milk',
      'condensed milk',
      'evaporated milk',
      'milk powder',
      'milk solids',
      'milk protein',
    ],
    icon: 'Milk',
  },
  {
    code: 'eggs',
    displayName: 'Eggs',
    description: 'Eggs and egg products',
    commonNames: [
      'egg',
      'eggs',
      'albumin',
      'albumen',
      'lecithin',
      'lysozyme',
      'meringue',
      'mayonnaise',
      'mayo',
      'aioli',
      'egg white',
      'egg yolk',
      'whole egg',
      'dried egg',
      'egg powder',
      'egg solids',
    ],
    icon: 'Egg',
  },
  {
    code: 'soy',
    displayName: 'Soy',
    description: 'Soybeans and soy products',
    commonNames: [
      'soy',
      'soya',
      'soybean',
      'soybeans',
      'tofu',
      'tempeh',
      'miso',
      'edamame',
      'soy lecithin',
      'soy sauce',
      'tamari',
      'natto',
      'okara',
      'soy protein',
      'soy flour',
      'soy milk',
      'soy oil',
    ],
    icon: 'Bean',
  },
  {
    code: 'gluten',
    displayName: 'Gluten',
    description: 'Gluten-containing cereals (wheat, rye, barley, oats)',
    commonNames: [
      'gluten',
      'wheat',
      'flour',
      'semolina',
      'durum',
      'bulgur',
      'rye',
      'barley',
      'oats',
      'oat',
      'triticale',
      'bread',
      'bun',
      'roll',
      'bagel',
      'pita',
      'naan',
      'pasta',
      'noodle',
      'noodles',
      'spelt',
      'kamut',
      'couscous',
      'farro',
      'freekeh',
      'seitan',
      'malt',
      'wheat starch',
      'wheat germ',
      'wheat bran',
      'breadcrumb',
      'breadcrumbs',
      'crouton',
      'croutons',
    ],
    icon: 'Wheat',
  },
  {
    code: 'fish',
    displayName: 'Fish',
    description: 'Fish and fish products',
    commonNames: [
      'fish',
      'anchovy',
      'anchovies',
      'tuna',
      'salmon',
      'cod',
      'bass',
      'sardine',
      'sardines',
      'mackerel',
      'snapper',
      'barramundi',
      'basa',
      'haddock',
      'trout',
      'halibut',
      'tilapia',
      'herring',
      'pilchard',
      'plaice',
      'sole',
      'swordfish',
      'mahi',
      'dory',
      'whiting',
      'eel',
      'catfish',
      'perch',
      'carp',
      'fish sauce',
      'fish paste',
      'fish oil',
      'fish stock',
      'worcestershire sauce',
      'worcester sauce',
    ],
    icon: 'Fish',
  },
  {
    code: 'shellfish',
    displayName: 'Shellfish',
    description:
      'Shellfish (crustaceans and molluscs: prawns, crabs, lobsters, oysters, mussels, etc.)',
    commonNames: [
      'prawn',
      'prawns',
      'shrimp',
      'crab',
      'crabs',
      'lobster',
      'lobsters',
      'crayfish',
      'oyster',
      'oysters',
      'mussel',
      'mussels',
      'scallop',
      'scallops',
      'clam',
      'clams',
      'squid',
      'octopus',
      'abalone',
      'yabby',
      'yabbies',
      'marron',
      'bug',
      'moreton bay bug',
      'balmain bug',
      'cuttlefish',
      'whelk',
      'periwinkle',
      'langoustine',
      'barnacle',
      'crustacean',
      'crustaceans',
      'mollusc',
      'molluscs',
      'mollusk',
    ],
    icon: 'Fish',
  },
  {
    code: 'sesame',
    displayName: 'Sesame',
    description: 'Sesame seeds and sesame products',
    commonNames: [
      'sesame',
      'tahini',
      'sesame seed',
      'sesame seeds',
      'benne',
      'sesame oil',
      'sesame paste',
      'til',
      'gingelly',
      'til oil',
    ],
    icon: 'CircleDot',
  },
  {
    code: 'lupin',
    displayName: 'Lupin',
    description: 'Lupin and lupin products',
    commonNames: ['lupin', 'lupine', 'lupini', 'lupin flour', 'lupin seed', 'lupin protein'],
    icon: 'Flower',
  },
  {
    code: 'sulphites',
    displayName: 'Sulphites',
    description: 'Sulphites (sulfur dioxide and sulphites)',
    commonNames: [
      'sulphite',
      'sulphites',
      'sulfite',
      'sulfites',
      'sulfur dioxide',
      'sulphur dioxide',
      'sodium sulphite',
      'sodium sulfite',
      'sodium metabisulphite',
      'sodium metabisulfite',
      'potassium sulphite',
      'potassium sulfite',
      'potassium metabisulphite',
      'potassium bisulphite',
      'potassium bisulfite',
      'e220',
      'e221',
      'e222',
      'e223',
      'e224',
      'e225',
      'e226',
      'e227',
      'e228',
    ],
    icon: 'AlertTriangle',
  },
  {
    code: 'mustard',
    displayName: 'Mustard',
    description: 'Mustard seeds and mustard products',
    commonNames: [
      'mustard',
      'mustard seed',
      'mustard seeds',
      'mustard powder',
      'mustard oil',
      'mustard flour',
      'mustard leaf',
      'dijon',
      'wholegrain mustard',
    ],
    icon: 'Circle',
  },
];
